server:
    servlet:
        context-path: "/toolrentalapp/v1"
    port: 8080

spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none

application:
  tool-info:
    tool-info-map:
      CHNS:
        tooltype: Chainsaw
        brand: Stihl
      LADW:
        tooltype: Ladder
        brand: Werner
      JAKD:
        tooltype: Jackhammer
        brand: DeWalt
      JAKR:
        tooltype: Jackhammer
        brand: Ridgid
    tool-price-map:
      ladder:
        dailycharge: 1.99
        weekdaycharge: yes
        weekendcharge: yes
        holidaycharge: no
      chainsaw:
        dailycharge: 1.49
        weekdaycharge: yes
        weekendcharge: no
        holidaycharge: yes
      jackhammer:
        dailycharge: 2.99
        weekdaycharge: yes
        weekendcharge: no
        holidaycharge: no

